---
- name:  set default boot kernel
  shell: grub2-set-default 0 || sed -i s'/default=[0-9]/default=0/g' /etc/grub.conf

- name: reboot os
  # Send the reboot command
  #- shell: shutdown -r now "Ansible updates triggered"
  shell: echo "rebooting now......"
  listen: "reboot a host and wait for it to return"

- name: pause 30 seconds
  # This pause is mandatory, otherwise the existing control connection gets reused!
  pause: seconds=30
  listen: "reboot a host and wait for it to return"

- name: wait a host to return
  # Now we will run a local 'ansible -m ping' on this host until it returns.
  # This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
  local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10
  listen: "reboot a host and wait for it to return"
